
'use client'


import { useAppDispatch, useAppSelector } from '@/store';
import { 
    addOne, 
    initCounterState, 
    substractOne 
} from '@/store/counter/CounterSlice';

import { useEffect } from 'react';

import { 
    IoArchive, 
    IoCartOutline, 
    IoCartSharp 
} from "react-icons/io5"

interface CartCounterProps {
    initialValue?: number
}

// Generated by https://quicktype.io
export interface CounterResponse {
    method: string;
    count: number;
}

const getApiCounter = async (): Promise<CounterResponse> => {
    const data = await fetch('/api/counter').then(res => res.json());
    return data
}


export const CartCounter = ({ initialValue }: CartCounterProps ) => {

    const counter = useAppSelector( state => state.counter.count )
    const dispatch = useAppDispatch()
    
    // const [counter, setCounter] = useState<number>( initialValue )

    useEffect(() => {
        if (typeof initialValue === 'number') {
            dispatch(initCounterState(initialValue));
        } else {
            getApiCounter()
                .then(({ count }) => dispatch(initCounterState(count)));
        }
    },[dispatch, initialValue]);

    return (
        <div className="flex flex-col justify-center items-center">
            <span className="text-5xl mt-2">{ counter }</span>
            <div className="flex justify-between items-center gap-4 mt-2">
                <button
                    onClick={() => dispatch(substractOne())}
                    disabled={counter <= 0}
                    className="flex justify-center items-center text-white w-[100] bg-gray-900 hover:bg-gray-600 transition-all p-2 rounded cursor-pointer disabled:bg-gray-300 disabled:text-gray-600 disabled:cursor-not-allowed">
                    -1
                </button>
                <button
                    onClick={() => dispatch(addOne())}
                    disabled={counter >= 10}
                    className="flex justify-center items-center text-white w-[100] bg-gray-900 hover:bg-gray-600 transition-all p-2 rounded cursor-pointer disabled:bg-gray-300 disabled:text-gray-600 disabled:cursor-not-allowed">
                    +1
                </button>
            </div>
            <div className="fixed bottom-5 right-5">
                {
                    counter === 1 && (
                        <span className="flex justify-center items-center gap-3 text-green-600 bg-green-100 border-2 border-green-600 text-lg p-2 rounded">
                            <IoCartSharp size={ 30 } />
                            Tienes { counter } producto en el carrito
                        </span>
                    )
                }
                {
                    counter > 1 && counter < 10 && (
                        <span className="flex justify-center items-center gap-3 text-green-600 bg-green-100 border-2 border-green-600 text-lg p-2 rounded">
                            <IoCartSharp size={ 30 } />
                            Tienes { counter } productos en el carrito
                        </span>
                    )
                }
                {
                    counter === 10 && (
                        <span className="flex justify-center items-center gap-3 text-yellow-600 bg-yellow-100 border-2 border-yellow-600 text-lg p-2 rounded">
                            <IoArchive size={ 30 } />
                            Has alcanzado el máximo de productos en el carrito
                        </span>
                    )
                }
                {
                    counter === 0 && (
                        <span className="flex justify-center items-center gap-3 text-red-600 bg-red-100 border-2 border-red-600 text-lg p-2 rounded">
                            <IoCartOutline size={ 30 } />
                            No hay productos en el carrito
                        </span>
                    )
                }
            </div>
        </div>
    )
}
